# Generated by Django 5.1.2 on 2024-10-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_auto_20200617_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='reps',
            field=models.PositiveSmallIntegerField(default=0, help_text='Enter the average'),
        ),
    ]
